# Generated by Django 4.1.5 on 2023-04-17 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_alter_answers_author_alter_categories_author_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categories',
            name='author',
        ),
    ]
